2019-09-03 00:46:34,713 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 00:46:45,227 ERROR: Exception on /edit_profile [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 91, in edit_profile
    form=form)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: edit_profile.html
2019-09-03 13:42:41,488 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 13:42:45,896 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 18:19:36,775 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 18:36:46,935 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 18:38:00,462 ERROR: Exception on /user/Claire [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 78, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
AttributeError: 'User' object has no attribute 'posts'
2019-09-03 18:42:50,271 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 18:42:54,674 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 18:43:05,783 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 18:45:38,278 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:29]
2019-09-03 20:35:43,962 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:31]
2019-09-03 20:46:48,284 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:33:23,248 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:38:40,186 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:38:49,945 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:48:29,947 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:53:10,067 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:55:28,610 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:56:24,941 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:57:20,439 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 13:58:11,719 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:00:03,719 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:00:38,398 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:01:07,952 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:01:17,909 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:01:45,175 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:21:11,708 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:38:18,484 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:38:32,422 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:38:37,869 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
2019-09-04 14:38:44,792 ERROR: Exception on /1 [GET] [in c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\dreamcast\documents\blog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Dreamcast\Documents\blog\main\urls.py", line 149, in post
    post = Post.query.filter_by(id=post.id).first_or_404()
UnboundLocalError: local variable 'post' referenced before assignment
2019-09-04 14:39:55,890 INFO: Blog Network startup [in C:\Users\Dreamcast\Documents\blog\main\__init__.py:33]
